---
- name: Dell OS10
  hosts: Leaf1
  gather_facts: false
  collections:
    - dellemc.os10
    - community.general.log_plays
  tasks:
    - name: Ping
      dellos10_command:
        commands:
          - show version
      register: result

    - name: Output
      debug: var=result.stdout_lines
